In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)
slice2=arr[::2]
print(slice2)

[3 4 5 6]
[1 3 5 7 9]


In [2]:
rev_arr=arr[::-1]
print(rev_arr)

[9 8 7 6 5 4 3 2 1]


In [4]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0:3:2])
print(a[0::2])
print(a[1::])
print(a[2:,2:])
print(a[::,2])
print(a[:2,:3])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[11 12]]
[ 3  7 11]
[[1 2 3]
 [5 6 7]]


In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:1,1:3]
print(subarray)

[[2 3]]


In [2]:
Reversed_array=arr[::-1]
print(Reversed_array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [3]:
col1=arr[:,0]
print(col1)

[1 4 7]


In [4]:
row1=arr[0,:]
print(row1)

[1 2 3]


In [8]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[1:4])
print(arr[arr>25])
print(arr[[1,3]])


10
50
50
[20 30 40]
[30 40 50]
[20 40]


In [9]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6


In [11]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [13]:
result1=np.vstack((arr1,arr2))
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
result2=np.dstack((arr1,arr2))
print(result2)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [18]:

import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [19]:
arr1=np.array([1,2,3,4,5])
result=np.array_split(arr1,3)
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
arr2=np.array([[1,2,3],[4,5,6]])
result2=np.hsplit(arr2,3)
print(result2)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [21]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
result3=np.vsplit(arr3,3)
print(result3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [24]:
arr4=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
result4=np.dsplit(arr4,2)
print(result4)

[array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


In [1]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[6,2,9,7,1]
a=np.array(arr1)
b=np.array(arr2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[10 20 30 40 50]
[6 2 9 7 1]
[16 22 39 47 51]
[ 4 18 21 33 49]
[ 60  40 270 280  50]
[ 1.66666667 10.          3.33333333  5.71428571 50.        ]


In [3]:
print(a.dot(b))
sclr=3
print("Scalar Value:",sclr)
print("Array:",a)
print("Result:",a*sclr)

700
Scalar Value: 3
Array: [10 20 30 40 50]
Result: [ 30  60  90 120 150]


In [4]:
import numpy as np
a=np.array([[[10,20],[30,40]]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[[1 6]
  [0 4]]]


In [14]:
def my_func(x,y):
    if(x>y):
        return(x-y)
    else:
        return(x+y)
    arr1=[10, 20, 30, 40]
    arr2=[2, 10, 35, 25]
    vet_func=np.vectorize(my_func)
    print("Array1:",arr1)
    print("Array2:",arr2)
    print("Result:",vect_func(arr1,arr2))

In [15]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
    arr1=[10,20,30,40]
    arr2=[2,10,35,35]
    vet_func=np.vectorize(my_func)
    print("Array1:",arr1)
    print("Array2:",arr2)
    print("Result:",Vect_func(arr1,arr2))