In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
print("one dimensional array:",a)

one dimensional array: [1 2 3 4 5]


In [5]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
print("2 Dimensional array:",b)

2 Dimensional array: [[1 2 3 4]
 [5 6 7 8]]


In [7]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
d=np.random.random ((3,2))
print(d)

[[0.29837656 0.1919669 ]
 [0.27525031 0.80459155]
 [0.77801863 0.15905479]]


In [11]:
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [4]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [5]:
flat=arr.flatten()
print(arr)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [7]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

2
(3, 4)
int64
12


In [8]:
newtype=arr.astype('f')
print("\n convert array:\n",newtype)
print("\n converted array type:\n",newtype.dtype)



 convert array:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

 converted array type:
 float32


In [9]:
size=len(arr)
print("\n size of array:\n",size)


 size of array:
 3
